# Generated by Django 3.2.8 on 2021-10-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaProfile', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ownerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
