# Generated by Django 3.2.8 on 2021-10-29 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('mopId', models.AutoField(primary_key=True, serialize=False)),
                ('modeOfPayment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('dueDate', models.DateField()),
                ('NHIFNumber', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('payed', 'payed'), ('not_payed', 'not payed')], max_length=255)),
                ('modeOfPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.modeofpayment')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('saleId', models.AutoField(primary_key=True, serialize=False)),
                ('dueDate', models.DateField()),
                ('quantity', models.IntegerField()),
                ('sellingPrice', models.IntegerField()),
                ('medicineId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('paymentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.payment')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
